name: Deploy to GCP

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Terraform
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2.0.3 

      - run: terraform init
      
      - run: terraform apply -auto-approve
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
